Initial cleanup of ZeroTier install shell script
Signed-off-by: Terrance Robotham <nitemare@darenet.org>

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -1,3 +1,4 @@
+#!/bin/bash
 ENDOFSIGSTART=
 
 export PATH=/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin
@@ -31,41 +32,41 @@ echo
 
 SUDO=
 if [ "$UID" != "0" ]; then
-	if [ -e /usr/bin/sudo -o -e /bin/sudo ]; then
-		SUDO=sudo
-	else
-		echo '*** This quick installer script requires root privileges.'
-		exit 0
-	fi
+  if [ -e /usr/bin/sudo ] || [ -e /bin/sudo ]; then
+    SUDO=sudo
+  else
+    echo '*** This quick installer script requires root privileges.'
+    exit 1
+  fi
 fi
 
 # Detect MacOS and install .pkg file there
 if [ -e /usr/bin/uname ]; then
-	if [ "`/usr/bin/uname -s`" = "Darwin" ]; then
-		echo '*** Detected MacOS / Darwin, downloading and installing Mac .pkg...'
-		$SUDO rm -f "/tmp/ZeroTier One.pkg"
-		curl -s ${ZT_BASE_URL_HTTPS}dist/ZeroTier%20One.pkg >"/tmp/ZeroTier One.pkg"
-		$SUDO installer -pkg "/tmp/ZeroTier One.pkg" -target /
+  if [ "$(/usr/bin/uname -s)" = "Darwin" ]; then
+    echo '*** Detected MacOS / Darwin, downloading and installing Mac .pkg...'
+    $SUDO rm -f "/tmp/ZeroTier One.pkg"
+    curl -s ${ZT_BASE_URL_HTTPS}dist/ZeroTier%20One.pkg >"/tmp/ZeroTier One.pkg"
+    $SUDO installer -pkg "/tmp/ZeroTier One.pkg" -target /
 
-		echo
-		echo '*** Waiting for identity generation...'
+    echo
+    echo '*** Waiting for identity generation...'
 
-		while [ ! -f "/Library/Application Support/ZeroTier/One/identity.secret" ]; do
-			sleep 1
-		done
+    while [ ! -f "/Library/Application Support/ZeroTier/One/identity.secret" ]; do
+      sleep 1
+    done
 
-		echo
-		echo "*** Success! You are connected to port `cat '/Library/Application Support/ZeroTier/One/identity.public' | cut -d : -f 1` of Earth's planetary smart switch."
-		echo
+    echo
+    echo "*** Success! You are connected to port $(cut -d : -f 1 /Library/Application Support/ZeroTier/One/identity.public) of Earth's planetary smart switch."
+    echo
 
-		exit 0
-	fi
+    exit 0
+  fi
 fi
 
 # Detect already-installed on Linux
 if [ -f /usr/sbin/zerotier-one ]; then
-	echo '*** ZeroTier One appears to already be installed.'
-	exit 0
+  echo '*** ZeroTier One appears to already be installed.'
+  exit 1
 fi
 
 rm -f /tmp/zt-gpg-key
@@ -128,158 +129,160 @@ echo '*** Detecting Linux Distribution'
 echo
 
 if [ -f /etc/debian_version ]; then
-	dvers=`cat /etc/debian_version | cut -d '.' -f 1 | cut -d '/' -f 1`
-	$SUDO rm -f /tmp/zt-sources-list
+  dvers=$(cut -d '.' -f 1 /etc/debian_version | cut -d '/' -f 1)
+  $SUDO rm -f /tmp/zt-sources-list
 
-	if [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F trusty`" ]; then
-		echo '*** Found Ubuntu "trusty", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/trusty trusty main" >/tmp/zt-sources-list
-	elif [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F wily`" ]; then
-		echo '*** Found Ubuntu "wily", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/wily wily main" >/tmp/zt-sources-list
-	elif [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F xenial`" ]; then
-		echo '*** Found Ubuntu "xenial", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/xenial xenial main" >/tmp/zt-sources-list
-	elif [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F zesty`" ]; then
-		echo '*** Found Ubuntu "zesty", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/zesty zesty main" >/tmp/zt-sources-list
-	elif [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F precise`" ]; then
-		echo '*** Found Ubuntu "precise", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/precise precise main" >/tmp/zt-sources-list
-	elif [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F artful`" ]; then
-		echo '*** Found Ubuntu "artful", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/artful artful main" >/tmp/zt-sources-list
-	elif [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F bionic`" ]; then
-		echo '*** Found Ubuntu "bionic", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/bionic bionic main" >/tmp/zt-sources-list
-	elif [ -f /etc/lsb-release -a -n "`cat /etc/lsb-release 2>/dev/null | grep -F yakkety`" ]; then
-		echo '*** Found Ubuntu "yakkety", creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/yakkety yakkety main" >/tmp/zt-sources-list
-	elif [ "$dvers" = "6" -o "$dvers" = "squeeze" ]; then
-		echo '*** Found Debian "squeeze" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/squeeze squeeze main" >/tmp/zt-sources-list
-	elif [ "$dvers" = "7" -o "$dvers" = "wheezy" ]; then
-		echo '*** Found Debian "wheezy" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/wheezy wheezy main" >/tmp/zt-sources-list
-	elif [ "$dvers" = "8" -o "$dvers" = "jessie" ]; then
-		echo '*** Found Debian "jessie" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/jessie jessie main" >/tmp/zt-sources-list
-	elif [ "$dvers" = "9" -o "$dvers" = "stretch" ]; then
-		echo '*** Found Debian "stretch" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/stretch stretch main" >/tmp/zt-sources-list
-	elif [ "$dvers" = "10" -o "$dvers" = "11" -o "$dvers" = "sid" -o "$dvers" = "buster"]; then
-		echo '*** Found Debian "buster", or "sid" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
-		echo "deb ${ZT_BASE_URL_HTTP}debian/buster stretch main" >/tmp/zt-sources-list
-	else
-		echo "*** FAILED: unrecognized or ancient distribution: $dvers"
-		exit 1
-	fi
+  if [ -f /etc/lsb-release ] && grep -qF trusty /etc/lsb-release; then
+    echo '*** Found Ubuntu "trusty", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/trusty trusty main" >/tmp/zt-sources-list
+  elif [ -f /etc/lsb-release ] && grep -qF wily /etc/lsb-release; then
+    echo '*** Found Ubuntu "wily", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/wily wily main" >/tmp/zt-sources-list
+  elif [ -f /etc/lsb-release ] && grep -qF xenial /etc/lsb-release; then
+    echo '*** Found Ubuntu "xenial", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/xenial xenial main" >/tmp/zt-sources-list
+  elif [ -f /etc/lsb-release ] && grep -qF zesty /etc/lsb-release; then
+    echo '*** Found Ubuntu "zesty", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/zesty zesty main" >/tmp/zt-sources-list
+  elif [ -f /etc/lsb-release ] && grep -qF precise /etc/lsb-release; then
+    echo '*** Found Ubuntu "precise", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/precise precise main" >/tmp/zt-sources-list
+  elif [ -f /etc/lsb-release ] && grep -qF artful /etc/lsb-release; then
+    echo '*** Found Ubuntu "artful", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/artful artful main" >/tmp/zt-sources-list
+  elif [ -f /etc/lsb-release ] && grep -qF bionic /etc/lsb-release; then
+    echo '*** Found Ubuntu "bionic", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/bionic bionic main" >/tmp/zt-sources-list
+  elif [ -f /etc/lsb-release ] && grep -qF yakkety /etc/lsb-release; then
+    echo '*** Found Ubuntu "yakkety", creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/yakkety yakkety main" >/tmp/zt-sources-list
+  elif [ "$dvers" = "6" ] || [ "$dvers" = "squeeze" ]; then
+    echo '*** Found Debian "squeeze" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/squeeze squeeze main" >/tmp/zt-sources-list
+  elif [ "$dvers" = "7" ] || [ "$dvers" = "wheezy" ]; then
+    echo '*** Found Debian "wheezy" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/wheezy wheezy main" >/tmp/zt-sources-list
+  elif [ "$dvers" = "8" ] || [ "$dvers" = "jessie" ]; then
+    echo '*** Found Debian "jessie" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/jessie jessie main" >/tmp/zt-sources-list
+  elif [ "$dvers" = "9" ] || [ "$dvers" = "stretch" ]; then
+    echo '*** Found Debian "stretch" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/stretch stretch main" >/tmp/zt-sources-list
+  elif [ "$dvers" = "10" ] || [ "$dvers" = "11" ] || [ "$dvers" = "sid" ] || [ "$dvers" = "buster" ]; then
+    echo '*** Found Debian "buster", or "sid" (or similar), creating /etc/apt/sources.list.d/zerotier.list'
+    echo "deb ${ZT_BASE_URL_HTTP}debian/buster stretch main" >/tmp/zt-sources-list
+  else
+    echo "*** FAILED: unrecognized or ancient distribution: $dvers"
+    exit 1
+  fi
 
-	$SUDO mv -f /tmp/zt-sources-list /etc/apt/sources.list.d/zerotier.list
-	$SUDO chown 0 /etc/apt/sources.list.d/zerotier.list
-	$SUDO chgrp 0 /etc/apt/sources.list.d/zerotier.list
-	$SUDO apt-key add /tmp/zt-gpg-key
+  $SUDO mv -f /tmp/zt-sources-list /etc/apt/sources.list.d/zerotier.list
+  $SUDO chown 0 /etc/apt/sources.list.d/zerotier.list
+  $SUDO chgrp 0 /etc/apt/sources.list.d/zerotier.list
+  $SUDO apt-key add /tmp/zt-gpg-key
 
-	echo
-	echo '*** Installing zerotier-one package...'
+  echo
+  echo '*** Installing zerotier-one package...'
 
-	# Pre-1.1.6 Debian package did not properly enumerate its files, causing
-	# problems when we try to replace it. So just delete them to force.
-	if [ -d /var/lib/zerotier-one ]; then
-		$SUDO rm -f /etc/init.d/zerotier-one /etc/systemd/system/multi-user.target.wants/zerotier-one.service /var/lib/zerotier-one/zerotier-one /usr/local/bin/zerotier-cli /usr/bin/zerotier-cli /usr/local/bin/zero
-	fi
+  # Pre-1.1.6 Debian package did not properly enumerate its files, causing
+  # problems when we try to replace it. So just delete them to force.
+  if [ -d /var/lib/zerotier-one ]; then
+    $SUDO rm -f /etc/init.d/zerotier-one /etc/systemd/system/multi-user.target.wants/zerotier-one.service /var/lib/zerotier-one/zerotier-one /usr/local/bin/zerotier-cli /usr/bin/zerotier-cli /usr/local/bin/zero
+  fi
 
-	cat /dev/null | $SUDO apt-get update
-	cat /dev/null | $SUDO apt-get install -y zerotier-one
-elif [ -f /etc/SuSE-release -o -f /etc/suse-release -o -f /etc/SUSE-brand -o -f /etc/SuSE-brand -o -f /etc/suse-brand ]; then
-	echo '*** Found SuSE, adding zypper YUM repo...'
-	cat /dev/null | $SUDO zypper addrepo -t YUM -g ${ZT_BASE_URL_HTTP}redhat/el/7 zerotier
-	cat /dev/null | $SUDO rpm --import /tmp/zt-gpg-key
+  cat /dev/null | $SUDO apt-get update
+  cat /dev/null | $SUDO apt-get install -y zerotier-one
+elif [ -f /etc/SuSE-release ] || [ -f /etc/suse-release ] || [ -f /etc/SUSE-brand ] || [ -f /etc/SuSE-brand ] || [ -f /etc/suse-brand ]; then
+  echo '*** Found SuSE, adding zypper YUM repo...'
+  cat /dev/null | $SUDO zypper addrepo -t YUM -g ${ZT_BASE_URL_HTTP}redhat/el/7 zerotier
+  cat /dev/null | $SUDO rpm --import /tmp/zt-gpg-key
 
-	echo
-	echo '*** Installing zeortier-one package...'
+  echo
+  echo '*** Installing zeortier-one package...'
 
-	cat /dev/null | $SUDO zypper install -y zerotier-one
+  cat /dev/null | $SUDO zypper install -y zerotier-one
 elif [ -d /etc/yum.repos.d ]; then
-	baseurl="${ZT_BASE_URL_HTTP}redhat/el/7"
-	if [ -n "`cat /etc/redhat-release 2>/dev/null | grep -i fedora`" ]; then
-		echo "*** Found Fedora, creating /etc/yum.repos.d/zerotier.repo"
-		baseurl="${ZT_BASE_URL_HTTP}redhat/fc/22"
-	elif [ -n "`cat /etc/redhat-release 2>/dev/null | grep -i centos`" -o -n "`cat /etc/redhat-release 2>/dev/null | grep -i enterprise`" ]; then
-		echo "*** Found RHEL/CentOS, creating /etc/yum.repos.d/zerotier.repo"
-		baseurl="${ZT_BASE_URL_HTTP}redhat/el/\$releasever"
-	elif [ -n "`cat /etc/system-release 2>/dev/null | grep -i amazon`" ]; then
-		echo "*** Found Amazon (CentOS/RHEL based), creating /etc/yum.repos.d/zerotier.repo"
-		baseurl="${ZT_BASE_URL_HTTP}redhat/amzn1/2016.03"
-	else
-		echo "*** Found unknown yum-based repo, using el/7, creating /etc/yum.repos.d/zerotier.repo"
-	fi
+  baseurl="${ZT_BASE_URL_HTTP}redhat/el/7"
+  if grep -qi fedora /etc/redhat-release; then
+    echo "*** Found Fedora, creating /etc/yum.repos.d/zerotier.repo"
+    baseurl="${ZT_BASE_URL_HTTP}redhat/fc/22"
+  elif grep -qi centos /etc/redhat-release || grep -qi enterprise /etc/redhat-release; then
+    echo "*** Found RHEL/CentOS, creating /etc/yum.repos.d/zerotier.repo"
+    baseurl="${ZT_BASE_URL_HTTP}redhat/el/\$releasever"
+  elif grep -qi amazon /etc/system-release; then
+    echo "*** Found Amazon (CentOS/RHEL based), creating /etc/yum.repos.d/zerotier.repo"
+    baseurl="${ZT_BASE_URL_HTTP}redhat/amzn1/2016.03"
+  else
+    echo "*** Found unknown yum-based repo, using el/7, creating /etc/yum.repos.d/zerotier.repo"
+  fi
 
-	$SUDO rpm --import /tmp/zt-gpg-key
+  $SUDO rpm --import /tmp/zt-gpg-key
 
-	$SUDO rm -f /tmp/zerotier.repo
-	echo '[zerotier]' >/tmp/zerotier.repo
-	echo 'name=ZeroTier, Inc. RPM Release Repository' >>/tmp/zerotier.repo
-	echo "baseurl=$baseurl" >>/tmp/zerotier.repo
-	echo 'enabled=1' >>/tmp/zerotier.repo
-	echo 'gpgcheck=1' >>/tmp/zerotier.repo
+  $SUDO rm -f /tmp/zerotier.repo
+  {
+    echo '[zerotier]'
+    echo 'name=ZeroTier, Inc. RPM Release Repository'
+    echo "baseurl=$baseurl"
+    echo 'enabled=1'
+    echo 'gpgcheck=1'
+  } >>/tmp/zerotier.repo
 
-	$SUDO mv -f /tmp/zerotier.repo /etc/yum.repos.d/zerotier.repo
-	$SUDO chown 0 /etc/yum.repos.d/zerotier.repo
-	$SUDO chgrp 0 /etc/yum.repos.d/zerotier.repo
+  $SUDO mv -f /tmp/zerotier.repo /etc/yum.repos.d/zerotier.repo
+  $SUDO chown 0 /etc/yum.repos.d/zerotier.repo
+  $SUDO chgrp 0 /etc/yum.repos.d/zerotier.repo
 
-	echo
-	echo '*** Installing zerotier-one package...'
+  echo
+  echo '*** Installing zerotier-one package...'
 
-	if [ -e /usr/bin/dnf ]; then
-		cat /dev/null | $SUDO dnf install -y zerotier-one
-	else
-		cat /dev/null | $SUDO yum install -y zerotier-one
-	fi
+  if [ -e /usr/bin/dnf ]; then
+    cat /dev/null | $SUDO dnf install -y zerotier-one
+  else
+    cat /dev/null | $SUDO yum install -y zerotier-one
+  fi
 fi
 
 $SUDO rm -f /tmp/zt-gpg-key
 
 if [ ! -e /usr/sbin/zerotier-one ]; then
-	echo
-	echo '*** Package installation failed! Unfortunately there may not be a package'
-	echo '*** for your architecture or distribution. For the source go to:'
-	echo '*** https://github.com/zerotier/ZeroTierOne'
-	echo
-	exit 1
+  echo
+  echo '*** Package installation failed! Unfortunately there may not be a package'
+  echo '*** for your architecture or distribution. For the source go to:'
+  echo '*** https://github.com/zerotier/ZeroTierOne'
+  echo
+  exit 1
 fi
 
 echo
 echo '*** Enabling and starting zerotier-one service...'
 
-if [ -e /usr/bin/systemctl -o -e /usr/sbin/systemctl -o -e /sbin/systemctl -o -e /bin/systemctl ]; then
-	$SUDO systemctl enable zerotier-one
-	$SUDO systemctl start zerotier-one
-	if [ "$?" != "0" ]; then
-		echo
-		echo '*** Package installed but cannot start service! You may be in a Docker'
-		echo '*** container or using a non-standard init service.'
-		echo
-		exit 1
-	fi
+if [ -e /usr/bin/systemctl ] || [ -e /usr/sbin/systemctl ] || [ -e /sbin/systemctl ] || [ -e /bin/systemctl ]; then
+  $SUDO systemctl enable zerotier-one
+  $SUDO systemctl start zerotier-one
+  if [ "$?" != "0" ]; then
+    echo
+    echo '*** Package installed but cannot start service! You may be in a Docker'
+    echo '*** container or using a non-standard init service.'
+    echo
+    exit 1
+  fi
 else
-	if [ -e /sbin/update-rc.d -o -e /usr/sbin/update-rc.d -o -e /bin/update-rc.d -o -e /usr/bin/update-rc.d ]; then
-		$SUDO update-rc.d zerotier-one defaults
-	else
-		$SUDO chkconfig zerotier-one on
-	fi
-	$SUDO /etc/init.d/zerotier-one start
+  if [ -e /sbin/update-rc.d ] || [ -e /usr/sbin/update-rc.d ] || [ -e /bin/update-rc.d ] || [ -e /usr/bin/update-rc.d ]; then
+    $SUDO update-rc.d zerotier-one defaults
+  else
+    $SUDO chkconfig zerotier-one on
+  fi
+  $SUDO /etc/init.d/zerotier-one start
 fi
 
 echo
 echo '*** Waiting for identity generation...'
 
 while [ ! -f /var/lib/zerotier-one/identity.secret ]; do
-	sleep 1
+  sleep 1
 done
 
 echo
-echo "*** Success! You are ZeroTier address [ `cat /var/lib/zerotier-one/identity.public | cut -d : -f 1` ]."
+echo "*** Success! You are ZeroTier address [ $(cut -d : -f 1 /var/lib/zerotier-one/identity.public) ]."
 echo
 
 exit 0
